### ISSUE TITLE
windows下调用出现:默认库“MSVCRTD”与其他库的使用冲突；以及无法解析的外部符号tuntap_open,tuntap_read,tuntap_write...

### ISSUE THREAD

**Issue by limitcool** [ChingCdesu/n2n-rust#1]
clang version 17.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
![image](https://github.com/ChingCdesu/n2n-rust/assets/88604249/0b3a83af-f210-4935-a946-d3d4a34f0472)

**Comment by ChingCdesu** [comment]
看上去像cmake在配置时宏定义没加上，我现在手边没Windows，今晚回去看

**Comment by ChingCdesu** [comment]
最新的提交上修复了，你再尝试一下

**Comment by limitcool** [comment]
我执行了cargo clean ,之后执行cargo run,报错已改变,似乎是缺少winsock2.h
![image](https://github.com/ChingCdesu/n2n-rust/assets/88604249/80467d38-7b98-479f-b425-5f5fd21a9c6e)
![image](https://github.com/ChingCdesu/n2n-rust/assets/88604249/edfa02ee-b2b8-46ef-a465-f434650df1de)
![image](https://github.com/ChingCdesu/n2n-rust/assets/88604249/939c6e86-d0ab-4df6-b7ab-d821c8ecc76e)

**Comment by ChingCdesu** [comment]
应该和你自己的本地配置有关，你的msvc找不到winsock2.h
